# api-gateway
# Autor: Martin Diaz
#
# Puerto central expuesto al frontend. 
# Todas las peticiones deben ingresar por el puerto 8080.
server.port=8080
spring.application.name=api-gateway

# --- RUTAS DE ENRUTAMIENTO (ROUTES) ---

# Ruta 1: Microservicio de Usuarios (Puerto 8081)
spring.cloud.gateway.routes[0].id=ms-usuarios
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/usuarios/**

# Ruta 2: Microservicio de Agenda (Puerto 8084)
spring.cloud.gateway.routes[1].id=ms-agenda
spring.cloud.gateway.routes[1].uri=http://localhost:8084
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/agenda/**

# Ruta 3: Microservicio de Fichas Clínicas (Puerto 8085)
spring.cloud.gateway.routes[2].id=ms-fichas-clinicas
spring.cloud.gateway.routes[2].uri=http://localhost:8085
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/fichas/**

# Ruta 4: Microservicio de Mascotas (Puerto 8086)
spring.cloud.gateway.routes[3].id=ms-mascotas
spring.cloud.gateway.routes[3].uri=http://localhost:8086
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/mascotas/**

# Ruta 5: Microservicio de Sucursales (Puerto 8087)
spring.cloud.gateway.routes[4].id=ms-sucursales
spring.cloud.gateway.routes[4].uri=http://localhost:8087
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/sucursales/**